import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Embodied Intelligence textbook
  tutorialSidebar: [
      {
      type: 'category',
      label: 'Foundations',
      items: ['foundations/index'],
    },
    {
      type: 'category',
      label: 'Simulation',
      items: ['simulation/index'],
    },
    {
      type: 'category',
      label: 'Perception',
      items: ['perception/index'],
    },
    {
      type: 'category',
      label: 'VLA',
      items: ['vla/index'],
    },
  ],
};

export default sidebars;
